# Generated by Django 5.0 on 2024-01-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_activate',
            field=models.BooleanField(default=True, verbose_name='учится'),
        ),
    ]
